# TITLE: Las labores de un cristiano

/"El justo sera salvado por su fe"/

* Confiar en Dios, y el tentar a Dios

La vida de un cristiano se basa en un solo precepto: seguir a nuestro salvador Jesus, el Cristo. La labor de un cristiano es, entonces, el transformar nuestro ser en uno mas cercano al hijo de Dios.

Uno de los puntos que mas resaltaba Jesucristo en su ensenanza y en su manera de actuar era la confianza en el Dios todopoderoso. La confianza de nuestro Senor en el Padre era tal que sacrifico su vida por la raza humana, manteniendo la firma esperanza de que este ultimo lo resuscitaria de entre los muertos.

Sin embargo, como se demuestra en la Santa Escritura, el enemigo puede corromper esta confianza y hacernos tentar a Dios.

** El discernimiento

La mejor defensa es el discernimiento del espiritu. Solo con la fuerza de Jesus podemos estar seguros de vencer toda tentacion.

** El camino peligroso y el atajo

Supongamos que nuestro trabajo esta en medio de un sendero peligroso. Deberiamos ir o no al trabajo? Como dije anteriormente, el Espirito Santo es el que tiene la verdadera respuesta. Sin embargo, vamos a considerar ciertos casos hipoteticos.

Si estamos seguros de que Dios nos quiere realizando ese trabajo y esa es la unica via hacia este, podemos estar en completa seguridad de que Su Presencia nos cuidara en el camino.

Si otro dia nos enteramos de que existe un camino mas seguro pero mas largo hacia nuestro trabajo, es nuestra responsabilidad dejar de usar el camino corto y peligroso, ya que andar por este ultimo seria tentar a Dios, ya que nuestro Padre nos esta ayudando por medio de un camino mas seguro. No podemos sentirnos nunca soberbios en plan de que 'ya yo he caminado por alli y no me ha pasado nada' ya que nuestra seguridad no esta dentro de nosotros, sino en la mano amorosa del Padre, por lo que siempre debemos estar atentos a sus mandatos.
