** Box Model

- Elements in CSS have outer (block, inline) and inner (normal, flex) display types.
- The full CSS box model only applies to block boxes, inline boxes use only some of the behaviour defined in the box model.
- Parts of the box:
  + Content box
  + Padding box
  + Border box
  + Margin box
- In the standard box model, the width and height attributes define the width and height of the /content box/. Any padding and border is then added to the total width and height taken up by the box (margin doesn't count towards its actual size).
- To turn on the alternative box model you set the /box-sizing/ attribute to *border-box*.
- Margin collapsing.
- Unlike margins, you cannot have negative amounts of padding -- the value must be 0 or a positive value.
- On inline boxes, width and height are ignored. Vertical margin, padding, and border are respected but do not change the relationship of other content to our inline box. Horizontal margin, padding, and border are respected and do cause other content to move away from the box.
- Inline-block provides a middle ground between block and inline. Inline-block boxes don't break onto a new line, but block box properties are respected.

** Backgrounds and borders

*** Background

- Large background images are not scaled down to fit the box. Small background images are tiled to fill the box.
- If you specify a *background-color* in addition to a *background-image* then the image displays on top of the color.
- *background-repeat* controls the tilling behaviour of images. Valid values are:
  1. no-repeat
  2. repeat-x
  3. repeat-y
  4. repeat
- *background-size* is used to fit the image inside the background. Valid values are:
  1. cover
  2. contain
  3. a <length>
  4. a <length> and a <percentage>
- *background-position* allows you to choose the position in which a background image appears on the box it is applied to. Valid values are:
  1. 1-value syntax:
     + center
     + top, left, bottom, right
     + A <length> or <percentage>. This specifies the X coordinate relative to the left edge, with the Y coordinate set to 50%
  2. 2-value syntax: one value defines X and the other defines Y.
     + One of the keywords top, left, bottom, right.
     + A <length> or <percentage>. If the other value is left or right, then this value defines Y, relative to the top edge. If the other value is top or bottom, then this value defines X, relative to the left edge. If both values are <length> or <percentage> values, then the first defines X and the second Y.
     + The default value is top left, or 0% 0%.
  3. 3-value syntax: Two values are keyword values, and the third is the offset for the preceding value.
     + The first value is one of the keywords values top, left, bottom, right, or center. If left or right are given here, then this defines X. If top or bottom are given, then this defines Y and the other keyword value defines X.
     + The single length or percentage value is an offset for the keyword value that precedes it. The combination of one keyword with two <length> or <percentage> values is not valid.
  4. 4-value syntax: The first and third values are keyword values defining X and Y. The second and fourth values are offsets for the preceding X and Y keywords values.
- *background-attachment* defines how the background scrolls when content scrolls. Valid values are:
  1. scroll (scrolls when page is scrolled, doesn't move when element is scrolled)
  2. fixed (doesn't scroll when page is scrolled, doesn't move when element is scrolled)
  3. local (scrolls when page is scrolled, moves when element is scrolled)

*** Recomendations

1. If text would be on top of a background image, make sure it has enough contrast to be read comfortably. Also, add a background color where text could be read in case the image doesn't load.

*** Borders





