* [2020-03-29] Third day without internet. Am going crazy... not! Felt blue throught the day, though. I want to be more grateful for all the great things in my life. Thanks God, for all the wonderful beings I've met. Gave my modem to Samuel for testing. He also gave me something to think about. For now, I got a copy of SICP. Will this be the time I finally read it? Only time will tell. Ditched DOOM Emacs and came up with some macros. It's incredible how little effort is needed to come up with something utterly powerful and utterly incomprehensible. Couldn't make a loop macro. Speaking of DOOM, I found several secrets in Heartland and Baculus. My grandmother is well and that's great. Later, I spent, like, 20 minutes looking for an english dictionary.
* [2020-03-30] God, forgive me for my sins, which are many. Jesus, have compassion of me, for your fidelity is eternal. I am all weakness and flesh, but you are the holy one of God. Be kind to those who love you like you have been since before time. Had trouble reading SICP. I want to be more patient, and have less expectations—to trust in God and only in God. 
