* Como romper la logica de tu mundo en dos momentos

Tokyo Ghoul y su sucesor, Tokyo Ghoul:re, fueron dos series que marcaron mi era universitaria. Aun recuerdo con emocion, y mucha confusion, la introduccion de Sasaki Haise y los quincy al principio de la segunda parte. "Que esta haciendo Ishida?" pense, "queremos ver a Kaneki, Touka y a los demas!" Por un segundo pense que Ishida habia perdido el juicio, pero me equivoque rotundamente: los quincy fueron personajes muy entranables y carismaticos - lo mejor de la secuela en mi opinion.

Sin embargo, pronto si llegaria una debacle en su narrativa. Esto era de esperarse, Ishida estaba agotado y en un punto emocional dificil, como el mismo reconoceria meses despues.

Mucho antes de esta declaracion, sin embargo, ocurrieron dos eventos que resaltaron la perdida de logica progresiva en el manga. Me refiero a la muerte de Tatara y a la no-muerte de Mitsuki. Pero antes de analizarlos por separado hay que entender como Ishida utilizaba la muerte en Tokyo Ghoul.

** Un seinen, no un shonen

Hay que recordar que Tokyo Ghoul es un seinen, no un shonen, aunque atraia a muchos fanaticos de este genero. Morir en un shonen es algo... bastante dificil. Las resurrecciones abundan en este genero. En Dragon Ball, por ejemplo, existen personajes con el poder para destruir PLANETAS enteros, mas pocos 

** Tatara, el personaje olvidado

Al igual que Noro, Tatara tenia un aura de misterio increible. Mas aun, este ultimo tenia lazos en el mundo de Tokyo Ghoul mas fuertes que el primero. A traves de varias conversaciones, conociamos que Tatara era el unico sobreviviente de un clan de ghouls chinos, cuyo lider era su hermano. El comandante de esta operacion, y el asesino de su familiar, fue el agente especial Ouji.

Esta pelea, entonces, tenia mucho detras de ella. Tatara se encontraba denuevo en medio de una situacion de exterminio por parte del CCG, y el grupo que fue a enfrentarlo estaba dirigido por el mismo Ouji! Esta pelea que se nos robo pudo haber sido una llena de sentimientos encontrados, y flashbacks que hubieran profundizado la historia de los ghouls chinos y del mismo Tatara.

** Mitsuki, la rompe logica

Al otro lado de la balanza, nos encontramos con una muerte que no fue pero debio haber sido. Despues de la huida de Kaneki y su grupo, Cabra, a las profundidades subterraneas, Reiji decide hacerles tiempo enfrentandose a dos palomas que les perseguian, Mitsuki y Aura. En medio de un gran enfrentamiento donde ambas partes hacen gala de su inteligencia y habilidad, Reiji consigue asestarles el golpe de gracia a traves de su ataque electrico, ante el cual las palomas caen como moscas.

Reiji a pesar de estar dos contra una, demuestra que, a pesar de sus constantes nerfeos por el mangaka, sigue siendo el mas experimentado en batalla, viendo mil veces mas tranquilo en esta que Mitsuki. El es un sobreviviente, ha luchado toda su vida, vio morir a su hermana sin poder hacer nada. Reiji estaba preparado para morir para proteger a Touka y a Kaneki pero logro una merecida victoria.

Sin embargo, de
