* The Magic of World of Warcraft

I can't remember how I felt when I learned about World of Warcraft, but dumbfounded is a good approximation.  here was something beyond Warcraft III, beyond that last adventure besides the legendary Rexxar against Admiral Proudmoore.


** The (absent) old heroes

As soon as I logged in, I was in a race. Where was Thrall? And Sylvanas? Where could I find REXXAR? I, a young troll hunter, kept myself busy killing young boars while dreaming of rubbing shoulders with those heroes I admired so much.

Those first levels were a struggle; hunters are known as the kings of leveling, but, until they learn how to tame beasts, they're pretty awkward to control; your distance attacks hit harder, though enemies close in quickly, forcing you to switch to melee attacks, which are inefficient. You start to 'kite' - moving a little after each shot - to maximize the damage you deal.

As soon as I got to Orgrimmar I cried of happiness - or awesomeness. The city of 'warriors', of which players have only glimpsed a little on Warcraft 3, have really come together. I tried 

The server I was on - Guerreros por la Paz or GPLP - had bugged pets: their 'Growl' ability didn't generate aggro as it should. So, even after getting an accomplice, I was meleeing enemies a lot. As I was doing most of the job, I put my talent points on Marksmanship, a talent tree that focused on ranged attacks, as opposed to Beast Mastery, which focused on pet improvements, the preferred leveling tree.

By The Burning Crusade, leveling in the old world was considerably easier than in vanilla. Lots of elite monsters have been nerfed, and some quests made more accesible.


