* Burning Crusade Most Memorable Quest Chains

In no particular order:

** The Cipher of Damnation

** Netherwing Ledge

Netherwing was one of the first daily-based factions in WoW, and it has always been a fan-favorite thanks to several factors. Unlike others of their kind, Netherwing allows you to grind 24/7 

** The Ring of Blood

It all began north of Nagrand with a simple concept: successive fights against ever tougher enemies, but sometimes that's all it takes. This quest chain put players face-to-face with the most dangerous gladiators of Outland in an arena run by the goblin Gurgthock and Wodin, his troll assistant.

  

Very simple, but pretty fun quest series that awarded plenty of experience and a nice weapon at the end. 

** Deathblow to the Legion

** Archmage Vargoth

Portable quest givers! I think this aspect is the one who struck the most to players at the time. It was certainly the highlight for me. Well, besides all the sweet, sweet lore on Kael'thas and the Kirin Tor.

The Archmage Vargoth starts at Area 51, where his apprentice is looking for help. 


** Showdown

Rexxar have always been a fan favorite, and his act during Burning Crusade didn't dissappoint. With his help, players brough the demise of several of the seven sons of Gruul the Dragonkiller, the zone's main antagonist.

Showdown is the name of the last quest in the chain, where we



** Hero of the Mag'har
